dap = require('dap');
vim.keymap.set('n', '<Leader>dc', function() dap.continue() end)
vim.keymap.set('n', '<Leader>dS', function() dap.status() end)
vim.keymap.set('n', '<Leader>ds', function() dap.step_over() end)
vim.keymap.set('n', '<Leader>di', function() dap.step_into() end)
vim.keymap.set('n', '<Leader>du', function() dap.up() end)
vim.keymap.set('n', '<Leader>dd', function() dap.down() end)
vim.keymap.set('n', '<Leader>do', function() dap.step_out() end)
vim.keymap.set('n', '<Leader>bb', function() dap.toggle_breakpoint() end)
vim.keymap.set('n', '<Leader>bc', function() dap.clear_breakpoints() end)
vim.keymap.set('n', '<Leader>dr', function() dap.repl.open() end)
vim.keymap.set('n', '<Leader>dR', function() dap.terminate() end)
vim.keymap.set('n', '<Leader>dt', function() dap.restart() end)
vim.keymap.set('n', '<Leader>dl', function() dap.run_last() end)
